[project]
name = "sb3-in-between"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pygame>=2.6.1",
    "stable-baselines3[extra]>=2.6.0",
    "swig>=4.3.1",
]
